version: '3.8'

services:
  shallot:
    build:
      context: .
      args:
        NGINX_UID: ${UID:-1000}
        NGINX_GID: ${GID:-1000}
    container_name: shallot-bot
    command: /start-docker.sh          # <-- Add this line
    ports:
      - "0.0.0.0:${SHALLOT_PORT:-9443}:8443"
    volumes:
      - ./shallotbot/data/:/app/data/
      - ./shallotbot/certs/:/opt/shallot/certs/
      - ./shallotbot/.env:/opt/shallot/.env:ro
      - ./shallotbot/logs/:/app/logs/
    environment:
      NGINX_UID: ${UID:-1000}
      NGINX_GID: ${GID:-1000}
    restart: unless-stopped
